name: Publish qwc-uwsgi-base docker image

on: [push]

jobs:

    build:
      runs-on: ubuntu-latest
      steps:

      - uses: actions/checkout@master

      - name: Get version tag
        id: get_tag
        run: |
          if [ ${{ startsWith(github.ref, 'refs/tags/') }} = true ]; then
            echo "alpine_tag=${GITHUB_REF:10}" >>$GITHUB_OUTPUT
            echo "ubuntu_tag=${GITHUB_REF:10}" >>$GITHUB_OUTPUT
          else
            echo "alpine_tag=latest" >>$GITHUB_OUTPUT
            echo "ubuntu_tag=latest" >>$GITHUB_OUTPUT
          fi

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and publish Alpine docker image
        uses: elgohr/Publish-Docker-Github-Action@v4
        with:
          name: sourcepole/qwc-uwsgi-base
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          tags: "${{ steps.get_tag.outputs.alpine_tag }},alpine-${{ steps.get_tag.outputs.alpine_tag }}"
          workdir: alpine
          platforms: linux/arm64,linux/amd64

      - name: Build and publish Ubuntu docker image
        uses: elgohr/Publish-Docker-Github-Action@v4
        with:
          name: sourcepole/qwc-uwsgi-base
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          tags: "ubuntu-${{ steps.get_tag.outputs.ubuntu_tag }}"
          workdir: ubuntu
          platforms: linux/arm64,linux/amd64
